<a id="1"></a>
# <p style="background-color:#034C53;font-family:newtimeroman;color:#FFF9ED;font-size:130%;text-align:center;border-radius:10px 10px;">IMPORTING LIBRARIES</p>

In [1]:
import pandas as pd
import numpy as np
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

# ========================================================
from NaiveBayesManual import NaiveBayesSimple

<a id="1"></a>
# <p style="background-color:#034C53;font-family:newtimeroman;color:#FFF9ED;font-size:130%;text-align:center;border-radius:10px 10px;">DATASET UNDERSAMPLING</p>

<a id="1"></a>
## <p style="background-color:#034C53;font-family:newtimeroman;color:#FFF9ED;font-size:110%;text-align:center;border-radius:10px 10px;">BACA DATASET</p>

In [2]:
data = pd.read_csv('./dataset (undersampling-oversampling)/dataset_sms_undersampling.csv')
data

label                                            Message  \
0         1  TSELpoin 777 kejutan POIN Hadiah Rp.15jt Resmi...   
1         1  Anda telah dipilih untuk menginap di 1 dari 25...   
2         0  Itu tidak apa-apa. Aku muncul untuk menanyakan...   
3         0  Tomorrow i am not going to theatre. . . So i c...   
4         1  FREE RING TONE just text "POLYS" to 87131. The...   
...     ...                                                ...   
2607      0                       No way I'm going back there!   
2608      1  ISI PULSA lebih untung di MYVPLUS! selain dpt ...   
2609      1  Anda dijamin Nokia Phone terbaru, 40GB iPod MP...   
2610      1  LAYANAN SMS. untuk kredit teks inklusif Anda, ...   
2611      1     ma, isi dl pulsa 20 rb di nmr ini 085337784732   

                                          clean_Message  
0     tselpoin kejut poin hadiah rpjt resmi xxxxx pi...  
1     pilih inap hotel top inggris less libur nila t...  
2       apaapa muncul bilang kau masuk tonght wen gadis  
3     tomorrow go theatr come wherev call tell come ...  
4     free ring tone text poli everi week get new to...  
...                                                 ...  
2607                                     way im go back  
2608  isi pulsa untung myvplus pulsa lsg voucher dis...  
2609  jamin nokia phone baru gb ipod mp player hadia...  
2610  layan sms kredit teks inklusif sila buka login...  
2611                                 isi pulsa rb nomor  

[2612 rows x 3 columns]

<a id="1"></a>
## <p style="background-color:#034C53;font-family:newtimeroman;color:#FFF9ED;font-size:110%;text-align:center;border-radius:10px 10px;">FEATURE ENGINEERING</p>

In [3]:
x = data['clean_Message']
y = data['label']

**Pakai TF-IDF dan N-Gram**

In [4]:
vec_TF_IDF = TfidfVectorizer(ngram_range=(1,1))
vec_TF_IDF.fit(x)

# x_tf_idf = vec_TF_IDF.transform(x)

TfidfVectorizer()

In [5]:
X = vec_TF_IDF.transform(x).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(2612, 5942))

In [6]:
data_tabular_tf_idf = pd.DataFrame(X,columns=vec_TF_IDF.get_feature_names_out())
data_tabular_tf_idf

aa  aah  aamiin  aathi   ab  abadi  abai  abbee  abbey  abdul  ...  \
0     0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   
1     0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   
2     0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   
3     0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   
4     0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   
...   ...  ...     ...    ...  ...    ...   ...    ...    ...    ...  ...   
2607  0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   
2608  0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   
2609  0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   
2610  0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   
2611  0.0  0.0     0.0    0.0  0.0    0.0   0.0    0.0    0.0    0.0  ...   

      zac  zarkasi  zebra  zed   zf  zjt  zoe  zouk   zs  ztkm  
0     0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  
1     0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  
2     0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  
3     0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  
4     0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  
...   ...      ...    ...  ...  ...  ...  ...   ...  ...   ...  
2607  0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  
2608  0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  
2609  0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  
2610  0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  
2611  0.0      0.0    0.0  0.0  0.0  0.0  0.0   0.0  0.0   0.0  

[2612 rows x 5942 columns]

In [7]:
y = np.array(y)
y

array([1, 1, 0, ..., 1, 1, 1], shape=(2612,))

**Simpan menjadi Pickle**

In [8]:
pickle.dump(vec_TF_IDF.vocabulary_,open("./file_pickle/feature_tf-idf_undersampling.sav", "wb"))

<a id="1"></a>
## <p style="background-color:#034C53;font-family:newtimeroman;color:#FFF9ED;font-size:110%;text-align:center;border-radius:10px 10px;">MODEL</p>

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

nb = NaiveBayesSimple()
model = nb.train(X_train, y_train)

y_pred = model.predict(X_test)

print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Simpan model ke dalam file
pickle.dump(model,open("./file_pickle/model_fraud_undersampling.sav","wb" ))

Akurasi: 0.9222737819025522

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.89      0.92       435
           1       0.90      0.95      0.92       427

    accuracy                           0.92       862
   macro avg       0.92      0.92      0.92       862
weighted avg       0.92      0.92      0.92       862

Confusion Matrix:
 [[389  46]
 [ 21 406]]


<a id="1"></a>
# <p style="background-color:#034C53;font-family:newtimeroman;color:#FFF9ED;font-size:130%;text-align:center;border-radius:10px 10px;">DATASET OVERSAMPLING</p>

<a id="1"></a>
## <p style="background-color:#034C53;font-family:newtimeroman;color:#FFF9ED;font-size:110%;text-align:center;border-radius:10px 10px;">BACA DATASET</p>

In [13]:
data = pd.read_csv('./dataset (undersampling-oversampling)/dataset_sms_oversampling.csv')
data

label                                            Message  \
0          0    Oh... Icic... K lor, den bertemu tempo hari ...   
1          1  4mths setengah harga sewa garis oranye & ponse...   
2          0   Ubah lagi... Ini e satu di sebelah eskalator ...   
3          1  MENDESAK! Nomor Ponsel Anda telah dianugerahi ...   
4          0             Have you been practising your curtsey?   
...      ...                                                ...   
18023      1  Customer service announcement. We recently tri...   
18024      1  Freemsg: 1-month unlimited free calls! Activat...   
18025      1  Gratis msg. Maaf, layanan yang Anda pesan dari...   
18026      0    Terima kasih atas harapan yang indah. Anda rock   
18027      0                              We r outside already.   

                                           clean_Message  
0                           oh icic k lor den temu tempo  
1      mths harga sewa garis oranye ponsel kamera bar...  
2                                 ubah e belah eskalator  
3      desak nomor ponsel anugerah hadiah ukp jamin h...  
4                                        practis curtsey  
...                                                  ...  
18023  custom servic announc recent tri make deliveri...  
18024  freemsg month unlimit free call activ smartcal...  
18025  gratis maaf layan pesan kirim milik kredit sil...  
18026                      terima kasih harap indah rock  
18027                                     outsid alreadi  

[18028 rows x 3 columns]

<a id="1"></a>
## <p style="background-color:#034C53;font-family:newtimeroman;color:#FFF9ED;font-size:110%;text-align:center;border-radius:10px 10px;">FEATURE ENGINEERING</p>

In [14]:
x = data['clean_Message']
y = data['label']

**Pakai TF-IDF dan N-Gram**

In [15]:
vec_TF_IDF = TfidfVectorizer(ngram_range=(1,1))
vec_TF_IDF.fit(x)

# x_tf_idf = vec_TF_IDF.transform(x)

TfidfVectorizer()

In [16]:
X = vec_TF_IDF.transform(x).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(18028, 10849))

In [17]:
data_tabular_tf_idf = pd.DataFrame(X,columns=vec_TF_IDF.get_feature_names_out())
data_tabular_tf_idf

____   aa  aah  aamiiiin  aamiin  aaniy  aaooooright  aathi  aathilov  \
0       0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   
1       0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   
2       0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   
3       0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   
4       0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   
...     ...  ...  ...       ...     ...    ...          ...    ...       ...   
18023   0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   
18024   0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   
18025   0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   
18026   0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   
18027   0.0  0.0  0.0       0.0     0.0    0.0          0.0    0.0       0.0   

       aathiwher  ...  zindgi  zjt  zoe  zogtoriu  zoom  zouk   zs  ztkm  \
0            0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   
1            0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   
2            0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   
3            0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   
4            0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   
...          ...  ...     ...  ...  ...       ...   ...   ...  ...   ...   
18023        0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   
18024        0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   
18025        0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   
18026        0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   
18027        0.0  ...     0.0  0.0  0.0       0.0   0.0   0.0  0.0   0.0   

       zyada  üll  
0        0.0  0.0  
1        0.0  0.0  
2        0.0  0.0  
3        0.0  0.0  
4        0.0  0.0  
...      ...  ...  
18023    0.0  0.0  
18024    0.0  0.0  
18025    0.0  0.0  
18026    0.0  0.0  
18027    0.0  0.0  

[18028 rows x 10849 columns]

In [18]:
y = np.array(y)
y

array([0, 1, 0, ..., 1, 0, 0], shape=(18028,))

**Simpan menjadi Pickle**

In [19]:
pickle.dump(vec_TF_IDF.vocabulary_,open("./file_pickle/feature_tf-idf_oversampling.sav", "wb"))

<a id="1"></a>
## <p style="background-color:#034C53;font-family:newtimeroman;color:#FFF9ED;font-size:110%;text-align:center;border-radius:10px 10px;">MODEL</p>

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

nb = NaiveBayesSimple()
model = nb.train(X_train, y_train)

y_pred = model.predict(X_test)

print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Simpan model ke dalam file
pickle.dump(model,open("./file_pickle/model_fraud_oversampling.sav","wb" ))

Akurasi: 0.9682352941176471

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.95      0.97      2942
           1       0.95      0.98      0.97      3008

    accuracy                           0.97      5950
   macro avg       0.97      0.97      0.97      5950
weighted avg       0.97      0.97      0.97      5950

Confusion Matrix:
 [[2802  140]
 [  49 2959]]
